version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"

  # Maintain dependencies for Composer
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "monthly"
    versioning-strategy: increase
    open-pull-requests-limit: 20
    rebase-strategy: "disabled"

  # Maintain dependencies for npm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    versioning-strategy: increase
    open-pull-requests-limit: 20
    rebase-strategy: "disabled"
    groups:
      alpinejs:
        patterns:
          - "alpinejs"
          - "@alpinejs/*"
      tiptap:
        patterns:
          - "@tiptap/*"
      vue:
        patterns:
          - "vue"
          - "@vue/*"
      vueuse:
        patterns:
          - "@vueuse/*"
